import typescript from "@rollup/plugin-typescript";
import svg from "rollup-plugin-svg-import";
import terser from "@rollup/plugin-terser";

import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "./src/main.ts",
  output: {
    file: "main.js",
    sourcemap: isProd ? false : "inline",
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    svg({ stringify: true }),
    typescript({
      allowSyntheticDefaultImports: true,
      sourceMap: !isProd,
      inlineSourceMap: !isProd,
      inlineSources: !isProd,
    }),
    nodeResolve({ browser: true }),
    commonjs({ include: "node_modules/**" }),
    isProd && terser(),
  ],
};
