import typescript from "@rollup/plugin-typescript";
import svg from "rollup-plugin-svg-import";

import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import { stringify } from "node:querystring";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: "./src/main.ts",
  output: {
    file: "main.js",
    sourcemap: "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    svg({ stringify: true }),
    typescript({ allowSyntheticDefaultImports: true }),
    nodeResolve({ browser: true }),
    commonjs({ include: "node_modules/**" }),
  ],
};
